#!/usr/bin/env bash
# rule_emit.sh — write a stack-scoped rule file into a project.
#
#   rule_emit.sh <lang> --project-dir <repo> [--force]
#
# WHAT A RULE FILE BUYS. `paths:` frontmatter scopes a rule to the files it is
# about, and a scoped rule stays out of context until one of those files is
# read — verified over three headless runs: loaded on a matching read, silent on
# a non-matching one. So the crew's house conventions can be stated once, in
# full, without every unrelated session paying for them.
#
# WHY IT IS SEPARATE FROM CREW GENERATION. An existing crew that predates rule
# files is not stale — it is complete apart from one document. `crew_check.sh`
# reports `RULE_FILE=missing` as an informational signal, and this script closes
# it in place: no agent is read, rewritten, or regenerated.
#
# The body is a skeleton the factory fills in from the stack profile. It is
# deliberately short — a rule nobody finishes reading is one nobody follows.
#
# Output: STATUS=WROTE|EXISTS|FAIL and PATH=<file>.
# Exits 0 when the file is in place, 1 on error, 2 on usage.
set -uo pipefail

LANG_ARG="${1:-}"
[ -n "$LANG_ARG" ] || { echo "usage: rule_emit.sh <lang> --project-dir <repo> [--force]" >&2; exit 2; }
shift

PROJECT_DIR="$PWD"
FORCE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --project-dir) PROJECT_DIR="${2:?--project-dir needs a directory}"; shift 2 ;;
    --force)       FORCE=1; shift ;;
    *) echo "usage: rule_emit.sh <lang> --project-dir <repo> [--force]" >&2; exit 2 ;;
  esac
done

[ -d "$PROJECT_DIR" ] || { echo "STATUS=FAIL"; echo "REASON=not-a-directory:$PROJECT_DIR"; exit 1; }

# Globs per stack. A rule scoped to the wrong extensions is worse than no rule:
# it loads where it does not apply and stays silent where it does.
case "$LANG_ARG" in
  bash|shell)   globs='["**/*.sh","**/*.bash","**/*.bats"]' ;;
  go)           globs='["**/*.go","**/go.mod"]' ;;
  python)       globs='["**/*.py","**/pyproject.toml"]' ;;
  typescript)   globs='["**/*.ts","**/*.tsx"]' ;;
  javascript)   globs='["**/*.js","**/*.jsx","**/*.mjs"]' ;;
  rust)         globs='["**/*.rs","**/Cargo.toml"]' ;;
  ruby)         globs='["**/*.rb","**/Gemfile"]' ;;
  java)         globs='["**/*.java"]' ;;
  csharp)       globs='["**/*.cs"]' ;;
  swift)        globs='["**/*.swift"]' ;;
  kotlin)       globs='["**/*.kt","**/*.kts"]' ;;
  php)          globs='["**/*.php"]' ;;
  sql|tsql)     globs='["**/*.sql"]' ;;
  *)            echo "STATUS=FAIL"; echo "REASON=no-glob-mapping:$LANG_ARG"; exit 1 ;;
esac

DEST="$PROJECT_DIR/.claude/rules/$LANG_ARG.md"

if [ -f "$DEST" ] && [ "$FORCE" -ne 1 ]; then
  echo "STATUS=EXISTS"
  echo "PATH=$DEST"
  exit 0
fi

mkdir -p "$(dirname "$DEST")" || { echo "STATUS=FAIL"; echo "REASON=cannot-create-dir"; exit 1; }

cat > "$DEST" <<EOF || { echo "STATUS=FAIL"; echo "REASON=write-failed"; exit 1; }
---
description: House conventions for $LANG_ARG in this repo, generated by crew-factory alongside the crew manifest.
paths: $globs
---

# $LANG_ARG conventions

Scoped by \`paths:\` above — this loads only when a $LANG_ARG file is read, and
costs nothing in any other session.

## Stack

<!-- crew-factory: fill from the stack profile — the test runner, linter,
     formatter and type checker actually installed, with the versions verified,
     not the ones the ecosystem defaults to. -->

## Conventions

<!-- crew-factory: the non-obvious ones only. Anything inferable from reading
     two files in this repo does not belong here. -->

## Commands

<!-- crew-factory: the exact commands that were run and passed, copied from the
     manifest's verified commands. A command nobody ran is a guess. -->
EOF

echo "STATUS=WROTE"
echo "PATH=$DEST"
exit 0
